accessible_charts: true
accessible_tabs: true
analytics:
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
country:
  name: Ghana
  adjective: Ghanaian
create_goals:
  layout: goal-by-target-vertical
  previous_next_links: false
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css:
  - /assets/css/custom.css
custom_js:
  - /assets/js/custom.js
data_edit_url: 'http://prose.io/#sdg-ghana/data/edit/develop/data/indicator_[id].csv'
data_fields:
  units: UNIT_MEASURE
  series: SERIES
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: sdg.secretariat@statsghana.gov.gh
  suggestions: sdg.secretariat@statsghana.gov.gh
  functional: sdg.secretariat@statsghana.gov.gh
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:sdg.secretariat@statsghana.gov.gh'
    translation_key: menu.contact_us
  - path: 'https://twitter.com/statsghana'
    translation_key: general.twitter
  - path: 'https://www.facebook.com/statsghana/'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Lorem ipsum
    content: |
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
      cursus est sed dapibus.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Nam vestibulum
    content: |
      Nam vestibulum, purus quis porttitor imperdiet, nisl sem mollis nisl, a
      interdum risus enim vitae tortor. Donec feugiat accumsan rutrum.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: Ghana data for Sustainable Development Goal indicators
  description: >-
    Click on each goal for Ghanaian Sustainable Development Goal global
    indicator data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: Ghana's National Reporting Platform Sustainable Development Goals
  description: Click on the *goals* below to see the most recent reported statistics.
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: default
graph_color_list: []
graph_color_number: 0
header:
  include: header-default.html
header_language_toggle: dropdown
hide_empty_metadata: false
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/sdg-ghana/data/tree/develop/indicator-config'
  translation_link: ''
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/sdg-ghana/data/tree/develop/meta'
  translation_link: 'https://hosted.weblate.org/languages/fr/sdg-translations/'
  language: en
  scopes:
    - national
    - global
  exclude_fields:
    - indicator_name
languages:
  - en
languages_public: []
logos: []
map_layers:
  - subfolder: regions_10
    label: 2010 Regions
    min_zoom: 3
    max_zoom: 8
    staticBorders: false
  - subfolder: regions_16
    label: 2016 Regions
    min_zoom: 3
    max_zoom: 8
    staticBorders: false
map_options:
  minZoom: 0
  maxZoom: 10
  tileURL: 'https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}'
  tileOptions:
    id: jawg-light
    accessToken: lCtbMZiG4tbVWl7uq9EEch1yphnuLx9JyZL2qZwoQJ26wAu73oK1NkU4K50AALkp
    attribution: >-
      <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps"
      target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a
      href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>
      contributors
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
  - path: /guidance
    translation_key: menu.guidance
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /about
    translation_key: Other indicators
    dropdown:
      - path: covid-indicators/
        translation_key: Covid indicators
      - path: gdp-indicators/
        translation_key: GDP indicators
metadata_edit_url: metadata
metadata_tabs: []
news:
  category_links: false
non_global_metadata: indicator.national_metadata
remote_data_prefix: 'https://sdg-ghana.github.io/data/'
reporting_status:
  title: ''
  description: ''
  disaggregation_tabs: true
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: 'https://github.com/sdg-ghana/site/tree/develop/_data'
  translation_link: ''
validate_indicator_config: false
validate_site_config: true
